import type { PageConfig } from '@/types'

export const mockPageConfig: PageConfig = {
  id: 'page-1',
  title: 'Voyage Co.',
  slug: 'voyage-co',
  description: 'Curated travel, events & experiences',
  theme: {
    background: { type: 'color', color: '#fafaf9' },
    fontFamily: 'Inter, sans-serif',
    primaryColor: '#4f46e5',
    maxWidth: '720px',
    fontColor: '#000000'
  },
  elements: [
    {
      id: 'elem-1',
      order: 'c',
      type: 'banner',
      visible: true,
      data: {
        title: 'Life is too short for ordinary',
        subtitle: 'Handpicked trips, live events, and bucket-list experiences — we sweat every detail so you just show up.',
        imageUrl: 'https://picsum.photos/seed/voyage-hero/1200/500',
        ctaText: 'Explore experiences',
        ctaUrl: '#',
        backgroundColor: '#1e1b4b',
        textColor: '#ffffff',
      },
    },
    {
      id: 'elem-2',
      order: 'f',
      type: 'social_links',
      visible: true,
      data: {
        heading: '',
        links: [
          { id: 'sl-1', order: 'd', platform: 'instagram', url: '#', label: 'Instagram' },
          { id: 'sl-2', order: 'j', platform: 'tiktok', url: '#', label: 'TikTok' },
          { id: 'sl-3', order: 'p', platform: 'youtube', url: '#', label: 'YouTube' },
          { id: 'sl-4', order: 'v', platform: 'twitter', url: '#', label: 'X / Twitter' },
        ],
        style: 'buttons',
        align: 'center',
      },
    },
    {
      id: 'elem-3',
      order: 'i',
      type: 'text_block',
      visible: true,
      data: {
        content: 'From rooftop cinema nights in New York to week-long surf retreats in Portugal — everything is small-group, carefully scouted, and unbothered by tourist traps.',
        align: 'center',
        variant: 'body',
      },
    },
    {
      id: 'elem-4',
      order: 'l',
      type: 'text_block',
      visible: true,
      data: {
        content: 'Featured experiences',
        align: 'left',
        variant: 'heading',
      },
    },
    {
      id: 'elem-5',
      order: 'n',
      type: 'card_grid',
      visible: true,
      data: {
        heading: '',
        columns: 2,
        cards: [
          {
            id: 'card-1',
            order: 'f',
            title: 'Bali Wellness Retreat',
            description: '7 days of yoga, meditation, and jungle hikes in Ubud. All-inclusive.',
            imageUrl: 'https://picsum.photos/seed/bali-retreat/600/450',
            link: '#',
            linkText: 'From $1,299',
          },
          {
            id: 'card-2',
            order: 'k',
            title: 'Tokyo Food & Culture',
            description: '5 days of hidden izakayas, dawn market runs, and neighborhood crawls.',
            imageUrl: 'https://picsum.photos/seed/tokyo-eats/600/450',
            link: '#',
            linkText: 'From $1,099',
          },
          {
            id: 'card-3',
            order: 'p',
            title: 'Northern Lights Iceland',
            description: 'Chase the aurora on a 4-night Reykjavík adventure with private guides.',
            imageUrl: 'https://picsum.photos/seed/iceland-aurora/600/450',
            link: '#',
            linkText: 'From $899',
          },
          {
            id: 'card-4',
            order: 'u',
            title: 'NYC Rooftop Salsa Night',
            description: 'Live band, craft cocktails, and dancing with the Manhattan skyline.',
            imageUrl: 'https://picsum.photos/seed/nyc-salsa/600/450',
            link: '#',
            linkText: '$85/person',
          },
        ],
      },
    },
    {
      id: 'elem-6',
      order: 'q',
      type: 'button_link',
      visible: true,
      data: {
        text: 'Browse all experiences',
        url: '#',
        style: 'outline',
        align: 'center',
        fullWidth: true,
      },
    },
    {
      id: 'elem-7',
      order: 's',
      type: 'text_block',
      visible: true,
      data: {
        content: 'Moments worth remembering',
        align: 'left',
        variant: 'heading',
      },
    },
    {
      id: 'elem-8',
      order: 'v',
      type: 'carousel',
      visible: true,
      data: {
        items: [
          {
            id: 'ci-1',
            order: 'g',
            imageUrl: 'https://picsum.photos/seed/patagonia-trek/900/500',
            title: 'Patagonia Trek — March 2024',
            caption: '23 guests, 9 days, zero complaints',
          },
          {
            id: 'ci-2',
            order: 'n',
            imageUrl: 'https://picsum.photos/seed/lisbon-food/900/500',
            title: 'Lisbon Food Tour — February 2024',
            caption: 'Sold out in 4 hours. Join the waitlist.',
          },
          {
            id: 'ci-3',
            order: 't',
            imageUrl: 'https://picsum.photos/seed/kyoto-blossom/900/500',
            title: 'Kyoto Cherry Blossom — April 2024',
            caption: 'Next run: April 2025. Early bird open.',
          },
        ],
        autoPlay: true,
        showDots: true,
      },
    },
    {
      id: 'elem-9',
      order: 'x',
      type: 'button_link',
      visible: true,
      data: {
        text: 'Get notified about new experiences',
        url: 'mailto:hello@voyage.co',
        style: 'primary',
        align: 'center',
        fullWidth: false,
      },
    },
  ],
}
